### ISSUE TITLE
crash on map load

### ISSUE THREAD

**Issue by x0x0x0x0x12** [maecry/asphyxia-cs2#10]
base is crashing when loading into a map

its crashing here:

void CS_FASTCALL H::FrameStageNotify(void* rcx, int nFrameStage)
{
	const auto oFrameStageNotify = hkFrameStageNotify.GetOriginal();
	F::OnFrameStageNotify(nFrameStage);

	return oFrameStageNotify(rcx, nFrameStage);
}

**Comment by x0x0x0x0x12** [comment]
fixed it : 
	namespace CLIENT
	{
		enum
		{
			CREATEMOVE = 5U,
			MOUSEINPUTENABLED = 12U,
			FRAMESTAGENOTIFY = 33, // Change from 32U to 33
		};
	}
}

but somehow the chams are only working for visible and non visible isnt working

**Comment by maecry** [comment]
the invis chams only work on debug atm, thanks for telling me that framestagenotify index is updated
