### ISSUE TITLE
iBones 

### ISSUE THREAD

**Issue by SlivcUX** [maecry/asphyxia-cs2#104]
Information: Here are some of the bone id's for newcomers 

Bone ids
- const int iBone = 1; // Pelvis
- const int iBone = 2; // Pelvis 2 <- I don't know it aims a tiny bit higher than pelvis
- const int iBone = 3; // Chest <- wrong, it aims a lil below actual chest
- const int iBone = 4; // Chest <- this is correct
- const int iBone = 5; // Neck <- corrected version
- const int iBone = 6; // Head
- const int iBone = 7; // Clavicle <- bone that connects shoulders (idk if anyone uses it)
- const int iBone = 8; // Right Shoulder
- const int iBone = 9; // Right Elbow
- const int iBone = 10; // Right Wrist (No one uses so keep it committed)

**_Note: some of these might be wrong, I'll correct them as I go (also add tag because it wouldn't let me)_**

**Yes, I know it's useless but it's for newcomers 😘**

**Comment by maecry** [comment]
You could just use discussion instead of issue lmao

**Comment by SlivcUX** [comment]
> You could just use discussion instead of issue lmao

oh shit mb
