### ISSUE TITLE
Bug on GetWorkingPath - Failed to find Module on MEM::GetModuleBaseFileName

### ISSUE THREAD

**Issue by ivanlr-design** [maecry/asphyxia-cs2#106]
After a debugging I found out that CRT::StringCopy() is crashing cs, also MEM::GetModuleBaseFileName(static_cast<HMODULE>(hDll), true); is returning null / nothing

**Comment by ivanlr-design** [comment]
I modified using own and it works, that's the only problem I encounter

**Comment by maecry** [comment]
Show debugger and stuffs, doesn't happen to my pc
