### ISSUE TITLE
why mad?

### ISSUE THREAD

**Issue by t0r-onion** [maecry/asphyxia-cs2#114]
why be mad for me not making a couple million variables to make your already dog code be even more dog? You actually have no idea how to code ngl.... and buddy fr closed the pull so I could not respond XD

**Comment by maecry** [comment]
Uhm? Aren't you the one being mad here tho

**Comment by maecry** [comment]
Also my repo my rule so ofc i can close it if i want xd, keep crying

**Comment by maecry** [comment]
oh yea, take my advice, you might need to learn english properly not coding. Even I'm not a grammar police yet still annoyed by your typing
