### ISSUE TITLE
TraceManager pattern can't be found while build with Clang17

### ISSUE THREAD

**Issue by M3351AN** [maecry/asphyxia-cs2#115]
**Describe the bug**
Signature here 
https://github.com/maecry/asphyxia-cs2/blob/86b35f3560cc362f3baf96d46b7fa12e3bbec2d6/cstrike/core/interfaces.cpp#L182

can be found while build with MSVC14.41(with warning that found not only one results)

however, it throws out pattern not found while build with Clang17.0.3

I dragged client.dll into IDA, and found 6 results with this signature

**To Reproduce**
1.Build with LLVM latest branch
2.Map dll into cs2.exe
3.ERROR

**Expected behavior**
Pattern should be searched properly

**Screenshots**
![417e917fc0cd1bb3ab55a31ebf8925d7](https://github.com/user-attachments/assets/58f54290-ef3b-4d6c-b8e9-6d27ac1bddd6)

**Additional context**
this pattern might have to update/complete, but for me, to deal the error i deleted a placeholder
like `4C 8B 3D ? ? ? ? 24 C9 0C 49 66 0F 7F 45 ?` -> `4C 8B 3D ? ? ? ? 24 C9 0C 49 66 0F 7F 45`
and it works properly on both MSVC&LLVM (still  [warning] found more than one occurrence ),so weird.

**Comment by maecry** [comment]
Urgh clang moment, I always want to drop it as compile time never as fast as msvc, will take a look later
