### ISSUE TITLE
game crashes after loading cheat dll

### ISSUE THREAD

**Issue by NUKED-RUST** [maecry/asphyxia-cs2#125]
**Describe the bug**
 if im new i will ned to learn even how to inject it on manual map or something with extreme injector 

**To Reproduce**
using extreme injector manual map

**Expected behavior**
open menu in main lobby

**Screenshots**
injected succesfully but closing game

**Additional context**

**Comment by SlivcUX** [comment]
use CS2 Injector from UC 

https://www.unknowncheats.me/forum/counter-strike-2-a/606455-cs2-injector.html

Extreme tends to cause issues.

**Comment by maecry** [comment]
#67
