### ISSUE TITLE
Outdated patterns

### ISSUE THREAD

**Issue by Adwhweu** [maecry/asphyxia-cs2#127]
Outdated patterns after game update

**Comment by gingerchicken** [comment]
Just having a poke about to see which patterns are outdated, so far it looks like the `SwapChain` one is outdated:

``
	// @ida:  #STR: "r_gpu_mem_stats", "-threads", "CTSListBase: Misaligned list\n", "CTSQueue: Misaligned queue\n", "Display GPU memory usage.", "-r_max_device_threads"
	SwapChain = **reinterpret_cast<ISwapChainDx11***>(MEM::ResolveRelativeAddress(MEM::FindPattern(RENDERSYSTEM_DLL, CS_XOR("66 0F 7F 0D ? ? ? ? 66 0F 7F 05 ? ? ? ? 0F 1F 40")), 0x4, 0x8));
``

If I find more, I will edit this comment with those too.

**Comment by sorryitsxanax** [comment]
`	namespace INPUTSYSTEM
	{
		enum
		{
			ISRELATIVEMOUSEMODE = 76U,
		};
	}`
	
	
`GameTraceManager = *reinterpret_cast<CGameTraceManager**>(MEM::GetAbsoluteAddress(MEM::FindPattern(CLIENT_DLL, CS_XOR("48 8B 0D ? ? ? ? 4C 8B C3 66 89 44 24")), 0x3, 0x0));
`

`GlobalVars = *reinterpret_cast<IGlobalVars**>(MEM::ResolveRelativeAddress(MEM::FindPattern(CLIENT_DLL, CS_XOR("48 8B 05 ? ? ? ? 8B 48 04 FF C1")), 0x3, 0x7));
`

`Input = *reinterpret_cast<CCSGOInput**>(MEM::ResolveRelativeAddress(MEM::FindPattern(CLIENT_DLL, CS_XOR("48 8B 0D ? ? ? ? 4C 8D 8F ? ? ? ? 45 33 FF")), 0x3, 0x7));
`

`SwapChain = **reinterpret_cast<ISwapChainDx11***>(MEM::ResolveRelativeAddress(MEM::FindPattern(RENDERSYSTEM_DLL, CS_XOR("66 0F 7F 0D ? ? ? ? 66 0F 7F 05 ? ? ? ? 48 89 2D ? ? ? ?")), 0x4, 0x8));
`


I just need the new structures now

**Comment by gingerchicken** [comment]
In addition these functions are no longer found (see hooks.cpp)

```c++
hkDrawObject.Create(MEM::FindPattern(SCENESYSTEM_DLL, CS_XOR("48 8B C4 53 41 54 41 55 48 81 EC ? ? ? ? 4D 63 E1")
```

**Comment by sorryitsxanax** [comment]
hkOverrideView is outdated too 

if im not wrong 

class CBaseUserCmdPB : public CBasePB
{
public:
	RepeatedPtrField_t<CSubtickMoveStep> subtickMovesField; // OK
	std::string* strMoveCrc; // All bellow moved to another class... 
	CInButtonStatePB* pInButtonState;
	CMsgQAngle* pViewAngles;
	std::int32_t nLegacyCommandNumber;
	std::int32_t nClientTick;
	float flForwardMove;
	float flSideMove;
	float flUpMove;
	std::int32_t nImpulse;
	std::int32_t nWeaponSelect;
	std::int32_t nRandomSeed;
	std::int32_t nMousedX;
	std::int32_t nMousedY;
	std::uint32_t nConsumedServerAngleChanges;
	std::int32_t nCmdFlags;
	std::uint32_t nPawnEntityHandle;

	int CalculateCmdCRCSize()
	{
		return MEM::CallVFunc<int, 7U>(this);
	}
};

**Comment by gingerchicken** [comment]
Yup, I was testing it and I got errors with the CreateMove hook for out-of-bounds read access with the `CBaseUserCmdPB`

**Comment by Tusso4** [comment]
MouseInputEnabled and FrameStageNotify sig or index??

**Comment by sorryitsxanax** [comment]
SO.... alot of things is broke, player controller ....

**Comment by Exlodium** [comment]
> Yup, I was testing it and I got errors with the CreateMove hook for out-of-bounds read access with the `CBaseUserCmdPB`
It's not getting UserCmds correctly

**Comment by sezzyaep** [comment]
public:
	PAD( 0x24 );
	int			m_server_type{};

is this outdated?

**Comment by ogpolak05** [comment]
DrawObject - 48 8B C4 48 89 50 ? 53

**Comment by fludar** [comment]
i crash when i open the menu, do y'all know how to fix IsRelativeMouseMode?

![image](https://github.com/user-attachments/assets/db08d9ec-06a3-4d9c-9edf-dd43b30ff675)

**Comment by fludar** [comment]
> > i crash when i open the menu, do y'all know how to fix IsRelativeMouseMode?
> > ![image](https://private-user-images.githubusercontent.com/74783457/375461984-db08d9ec-06a3-4d9c-9edf-dd43b30ff675.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1OTAzNzMsIm5iZiI6MTcyODU5MDA3MywicGF0aCI6Ii83NDc4MzQ1Ny8zNzU0NjE5ODQtZGIwOGQ5ZWMtMDZhMy00ZDljLTllZGYtZGQ0M2IzMGZmNjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDE5NTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTliYTAwZWJhMzExMTI4NWM1YWQ5OTkzNTAwNGM3NDcwM2ZjNjI1MzMxYjgyZjY0ODU2YmYwZTM2ZTQ2MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zO0yCFhoDxDd9Rck71YIA9y0ioYJBRe26yWtxu6BrmA)
> 
> ISRELATIVEMOUSEMODE = 76U

thanks! how did you find this?

**Comment by gingerchicken** [comment]
I remember reading it somewhere on unknowncheats, but I don't remember where.

**Comment by maecry** [comment]
since I'm so fking busy with life and my IRL work, u guys should prob find the needed stuffs on UC, either make PR or keep it to urself IDC, at this point I will just archive this repo soon as I don't really have the time to maintain it(you can see that @Exlodium is actually the one doing that for several months)

**Comment by Tusso4** [comment]
Anyone have GetPunchAngle and AllowCameraChange ??

**Comment by bebrikpopka** [comment]
> since I'm so fking busy with life and my IRL work, u guys should prob find the needed stuffs on UC, either make PR or keep it to urself IDC, at this point I will just archive this repo soon as I don't really have the time to maintain it(you can see that @Exlodium is actually the one doing that for several months)
plz teach me how to update

**Comment by maecry** [comment]
> plz teach me how to update

use ur brain, and why would I

**Comment by dankor33** [comment]
> > since I'm so fking busy with life and my IRL work, u guys should prob find the needed stuffs on UC, either make PR or keep it to urself IDC, at this point I will just archive this repo soon as I don't really have the time to maintain it(you can see that @Exlodium is actually the one doing that for several months) 
> 
> 
> 
> plz teach me how to update

Brother look at uc if you don't know how to use Ida

**Comment by Leg-rings** [comment]
QAngle_t GetViewAngles()
	{
		using fnGetViewAngles = std::int64_t(CS_FASTCALL*)(CCSGOInput*, std::int32_t);
		static auto oGetViewAngles = reinterpret_cast<fnGetViewAngles>(MEM::FindPattern(CLIENT_DLL, CS_XOR("4C 8B C1 85 D2 74 08 48 8D 05 ? ? ? ? C3")));

#ifdef CS_PARANOID
		CS_ASSERT(oGetViewAngles != nullptr);
#endif

		return *reinterpret_cast<QAngle_t*>(oGetViewAngles(this, 0));
	}

Getting viewangle crash in CCSGOInput

**Comment by maecry** [comment]
#67 read  title
