### ISSUE TITLE
Recontinuing asphyxia - looking for devs

### ISSUE THREAD

**Issue by kauri6** [maecry/asphyxia-cs2#128]
Me and my friend decided we want to recontinue this cheat as its very clean and we like the code. If anyone agrees and wants to recontinue this contact **kauri6** on discord. We are looking for reverse engineers as we can manage the rest. If we find people that wanna work we will make a fork and update it, we plan to make it a full cheat, with legit and basic rage functions. Hopefully this is ok with @maecry

**Comment by kauri6** [comment]
Right now we are attempting to update everything so it doesn't crash and failing horribly.

**Comment by Dezyrr** [comment]
Asphyxia is not discontinued afaik. 
Dude is just busy with life, create a PR if you make any changes or fixes.
