### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by yhqe** [maecry/asphyxia-cs2#13]
**Describe the bug**
nothing appears/happens when injecting

**To Reproduce**
use injector https://github.com/adamhlt/DLL-Injector (loadlibrary) to inject built dll into cs2.exe

**Expected behavior**
base loads

**Screenshots**
![image](https://github.com/maecry/asphyxia-cs2/assets/139268606/1956dc24-9f0d-4e25-9a2c-7c1f2f053cba)

**Additional context**
used multiple other loadlibrary injectors and same thing. i used debug and release builds, unmodified

**Comment by Dufiw** [comment]
Just use extreme injector and use LdrLoadDll Stub for the injection method

**Comment by maecry** [comment]
Vac block loadlib call, either find a way to bypass or -insecure launch option
