### ISSUE TITLE
outdated class

### ISSUE THREAD

**Issue by creatineloa** [maecry/asphyxia-cs2#15]
cusercmd has crash

**Comment by maecry** [comment]
fixed

**Comment by Ewu1x** [comment]
no fix crash

**Comment by maecry** [comment]
> no fix crash

Use proper english + tell me how to reproduce the crash

**Comment by Ewu1x** [comment]
when launching the resources, when they made the dll, I inject it into cs2, the game immediately crashes

**Comment by maecry** [comment]
> when launching the resources, when they made the dll, I inject it into cs2, the game immediately crashes

still missing information as i didnt crash, git pull the latest and try again or show where did you crash by attaching the debugger
