### ISSUE TITLE
CUserCmd

### ISSUE THREAD

**Issue by BuddDwyer-0x00** [maecry/asphyxia-cs2#17]
Cheat crashes when entering match / enabling bhop

CUserCmd is probably outdated

**Comment by Winens** [comment]
createmove's vtable index is updated to 14

**Comment by BuddDwyer-0x00** [comment]
thanks chief

**Comment by BuddDwyer-0x00** [comment]
> createmove's vtable index is updated to 14

Doesn't seem to work, any idea what might have been changed?

**Comment by Winens** [comment]
the parameters has been changed too. search in unkownncheats.
![image](https://github.com/maecry/asphyxia-cs2/assets/52735546/b91df38e-8ea6-4ea4-83a6-c0951ee841ad)

**Comment by BuddDwyer-0x00** [comment]
> the parameters has been changed too. search in unkownncheats. ![image](https://private-user-images.githubusercontent.com/52735546/290303153-b91df38e-8ea6-4ea4-83a6-c0951ee841ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzQzNjUsIm5iZiI6MTcwMjUzNDA2NSwicGF0aCI6Ii81MjczNTU0Ni8yOTAzMDMxNTMtYjkxZGYzOGUtOGVhNi00ZWE0LTgzYTYtYzA5NTFlZTg0MWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA2MDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNTc3MTM5ZmY5N2YzMWRiNTI3NDk4MmY0N2FkMmMzOTdjMzhjOTFjYTMyNzY4MmQ3NzBhYzY3OTlhYmFiYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UfBtsCsN-VXvSGP3I9-Rr2eTKn2ZEgvv3oWrIu2yczo)

couldn't find anything on UC, maybe i'm blind, any chance you could share what was changed?

**Comment by maecry** [comment]
i havent got time yet

> couldn't find anything on UC, maybe i'm blind, any chance you could share what was changed?
xref string on ida -> createmove and count the idx or calculate with bytes

**Comment by BuddDwyer-0x00** [comment]
> i havent got time yet to fix the base as i just received my new mainboard this week
> 
> > couldn't find anything on UC, maybe i'm blind, any chance you could share what was changed?
> 
> xref string on ida -> create move and count the idx or calculate with bytes

alright i'll look into it, source2 seems much more complicated to me so been kinda having a hard time learning all of this new stuff haha

**Comment by Winens** [comment]
> > the parameters has been changed too. search in unkownncheats. ![image](https://private-user-images.githubusercontent.com/52735546/290303153-b91df38e-8ea6-4ea4-83a6-c0951ee841ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzQzNjUsIm5iZiI6MTcwMjUzNDA2NSwicGF0aCI6Ii81MjczNTU0Ni8yOTAzMDMxNTMtYjkxZGYzOGUtOGVhNi00ZWE0LTgzYTYtYzA5NTFlZTg0MWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA2MDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNTc3MTM5ZmY5N2YzMWRiNTI3NDk4MmY0N2FkMmMzOTdjMzhjOTFjYTMyNzY4MmQ3NzBhYzY3OTlhYmFiYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UfBtsCsN-VXvSGP3I9-Rr2eTKn2ZEgvv3oWrIu2yczo)
> 
> couldn't find anything on UC, maybe i'm blind, any chance you could share what was changed?

i litereally just send you the parameters and are you saying that u couldnt find it?

**Comment by Winens** [comment]
```cpp
bool CS_FASTCALL H::CreateMove(CCSGOInput* pInput, void* unk,CUserCmd* pCmd)
```

**Comment by StephenIsTaken** [comment]
> ```cpp
> bool CS_FASTCALL H::CreateMove(CCSGOInput* pInput, void* unk,CUserCmd* pCmd)
> ```

You should make a pull request with everything fixed cuz its probably going to take maecry another week to fix his shit

**Comment by Winens** [comment]
do it yourself bro. its not hard and even if it is, you should learn to hack game, or your wont be able to continue your project too.

**Comment by maecry** [comment]
> > do it yourself bro. its not hard and even if it is, you should learn to hack game, or your wont be able to continue your project too.
> 
> I fixed it but i was just saying for all the other ppl

uhm then why don't you make a pr 🤔but anyway i did a quick fix + updated the class, the rest will be later
