### ISSUE TITLE
Console crash when injecting

### ISSUE THREAD

**Issue by Jopro1990** [maecry/asphyxia-cs2#24]
I am currently using extreme injector v3 and injected the built with manual map (nothing modified). The console opens up, and loads up and then crashes the entire game, the last line the console said was:
[31-01-2024 14:50:08] [core.cpp:121] renderer backend initialization completed

That's what happens when using the debug build, the release build just crashes my game, no console showing up.
![Screenshot 2024-01-31 145515](https://github.com/maecry/asphyxia-cs2/assets/129279032/4f7df6da-cba5-4cfd-9ae4-7be940bf97ef)

I am on win11 and AMD, does this change anything?

**Comment by maecry** [comment]
use loadlibrary call or "/Zc:threadSafeInit-" to enable thread-safe for manual mapping

**Comment by maecry** [comment]
and yea #3 duplicated

**Comment by Jopro1990** [comment]
> use loadlibrary call or "/Zc:threadSafeInit-" to enable thread-safe for manual mapping

How do i use loadlibary call on extreme injector or the "/Zc:threadSafeInit-"

**Comment by maecry** [comment]
> How do i use loadlibary call on extreme injector or the "/Zc:threadSafeInit-"
https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya
https://learn.microsoft.com/en-us/cpp/build/reference/zc-threadsafeinit-thread-safe-local-static-initialization?view=msvc-170

**Comment by Jopro1990** [comment]
> > How do i use loadlibary call on extreme injector or the "/Zc:threadSafeInit-"
> 
> https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya https://learn.microsoft.com/en-us/cpp/build/reference/zc-threadsafeinit-thread-safe-local-static-initialization?view=msvc-170

#yes but how do I use it? Implement into source?

**Comment by maecry** [comment]
> yes but how do I use it? Implement into source? Im new to this

write yourself a loadlibrary injector, or read premake5.lua 
note: vac block loadlibrary call so either "-insecure" or do the bypass same as this https://github.com/danielkrupinski/OneByteLdr mentioned

**Comment by Jopro1990** [comment]
> > yes but how do I use it? Implement into source? Im new to this
> 
> write yourself a loadlibrary injector, or read premake5.lua note: vac block loadlibrary call so either "-insecure" or do the bypass same as this https://github.com/danielkrupinski/OneByteLdr mentioned

i did write my own incetor, and now i get the gui, but if i load into a game and the map loads, it just crashes my game. Is the src outdated or smt?

**Comment by maecry** [comment]
attach the debugger and show where u crash

**Comment by Jopro1990** [comment]
> attach the debugger and show where u crash

the one in visual studio?

**Comment by maecry** [comment]
> the one in visual studio?

obviously, but honestly at this point you should uninstall it
