### ISSUE TITLE
Chams are crashing

### ISSUE THREAD

**Issue by tyackman** [maecry/asphyxia-cs2#29]
https://prnt.sc/EdGgIyoVfD7C

**Comment by maecry** [comment]
obviously the class/struct updated however i wont have time until the new year-end(lunar calendar)

**Comment by Exlodium** [comment]
I'll take a look later today. Will make a pull request if I manage to fix it

**Comment by DEFS9** [comment]
> I'll take a look later today. Will make a pull request if I manage to fix it

Can you work on https://github.com/alza54/opensource2 ? because it has aimbot, triggerbot & rcs and everything! it misses only  inventory changer from: https://github.com/bruhmoment21/cs2-sdk/tree/a024d82b81c62ddc62a3fc40c0a51110b27fa9a4/cs2cheat/src/game/skins (it was included in the paste).
