### ISSUE TITLE
SkeletonInstance

### ISSUE THREAD

**Issue by surowyncs2** [maecry/asphyxia-cs2#40]
Hello, i would like to know how to get boneArray from this source, i'm trying to do that for 6 hours but i found nothing.
Can someone help me pls ?

**Comment by maecry** [comment]
![msedge_FMCNDk0xTP](https://github.com/maecry/asphyxia-cs2/assets/52035116/9f480817-1e6b-4a12-a44b-6bb8a459031e)
It's not yet implemented, however I think after 10minute of browsing UC, you can find the idea how to implement that yourself

**Comment by surowyncs2** [comment]
yes, but `pPlayer->GetGameSceneNode()` return `nullptr`

**Comment by maecry** [comment]
> yes, but `pGameSceneNode->GetSkeletonInstance()` return `nullptr`

Do you read it from pawn? else I guess the GetSkeletonInstance() vtable is updated, try +/- idk will look into later

**Comment by Exlodium** [comment]
There is no m_boneArray schema in CModelState?

**Comment by Exlodium** [comment]
Both skeleton instance from asphyxia and the bone array in Modelstate works for me
`
class CModelState
{
public:
	MEM_PAD(0x80);
	BoneData_t*	m_pBones;
};
`
