### ISSUE TITLE
Render target view destroyed 

### ISSUE THREAD

**Issue by snLyy** [maecry/asphyxia-cs2#41]
**Describe the bug**
Render target view has been destroyed after changing the game resolution.

**To Reproduce**
1. Inject.
2. Change the game resolution.

**Expected behavior**
The render target view should persist after changing the game resolution.

**Screenshots**
No

**Additional context**
This issue likely stems from the render target view not being properly re-initialized or updated after the resolution change. Consider implementing a solution to recreate or update the render target view when the resolution changes to ensure its persistence.

**Comment by maecry** [comment]
I can change resolution fine tho so I don't know, will take a look later
