### ISSUE TITLE
Possible Aimbot using this base

### ISSUE THREAD

**Issue by malloc2k** [maecry/asphyxia-cs2#45]
**Describe the bug**

Its not really a bug, and because your discord link isn't working i was going to ask here how would it be possible to make an aimbot using this base, like getting view angles, bones, world to screen functions etc. 
Im relatively new to CS2 cheats and i believe your base is really good, but also really complex xD.
Thanks for the help in adnvance!

**Comment by maecry** [comment]
If you're asking those kind of questions, cs2 cheating isn't for you yet
