### ISSUE TITLE
Legitbot

### ISSUE THREAD

**Issue by lola123iuj** [maecry/asphyxia-cs2#50]
Make an legitbot with good aimbot and all that stuff you know smoothing and stuff. Can you add offsets from aimstar so It will be easier to add features.

**Comment by Zenixas** [comment]
> Make an legitbot with good aimbot and all that stuff you know smoothing and stuff. Can you add offsets from aimstar so It will be easier to add features.

This is a base to customize yourself, adding features would just result in it eventually becoming another shitty unoptimized cheat like AimStar is right now.


> Can you add offsets from aimstar so It will be easier to add features.
You saying it as if AimStar the one that creates offsets lol. It is already quite easy to add features as a lot of the heavy lifting has already been done here. 


Learn to code and create a fork if you want to have aimbot.

**Comment by XanaXCODE** [comment]
I'm having trouble getting bone data.. can you help me? I want to learn of course

**Comment by maecry** [comment]
> Make an legitbot with good aimbot and all that stuff you know smoothing and stuff. Can you add offsets from aimstar so It will be easier to add features.

You just want a free legitbot cheat huh? You're clearly clueless about whatever you said, anyway this a base so add it youself, I don't really care whether you pasted it or not



> I'm having trouble getting bone data.. can you help me? I want to learn of course

Yea I can help, lemme start reading your mind so can I know what kind of issues you're dealing with
