### ISSUE TITLE
How does obtaining bone data work?

### ISSUE THREAD

**Issue by XanaXCODE** [maecry/asphyxia-cs2#51]
I had asked a question but forgot to include it in another issue.

Anyway, I'm curious how the data structure for bone data is made and constructed.

I saw some information in another issue and wanted to test it and understand how it was done, but I couldn't understand some things (I'm a beginner at some things)

I used this to test:

```
struct CBoneData
{
	Vector_t Location;
	float Scale;
	Quaternion_t Rotation;
};

class CModelState
{
public:
	CS_CLASS_NO_INITIALIZER(CModelState);

	SCHEMA_ADD_FIELD(CBoneData*, GetBoneArray, "CModelState->m_boneArray");

	Vector_t GetBoneLocation(int index)
	{
		if (GetBoneArray() && index < 0)
			return nullptr;
		Vector_t pos = GetBoneArray()[index].Location;
		return pos;
	}
};

class CSkeletonInstance : public CGameSceneNode
{
public:
	CS_CLASS_NO_INITIALIZER(CSkeletonInstance);
	SCHEMA_ADD_FIELD(CModelState, GetModelState, "CSkeletonInstance->m_modelState");
};

```

from this : [Issue-40](https://github.com/maecry/asphyxia-cs2/issues/40#issuecomment-1956717482)

What I don't understand is how the CBoneData data is saved and what is the difference between getting data like this or with a bone data matrix?

Why I have a doubt about how the CBoneData data is taken is because I tested as you said in [Issue-40](https://github.com/maecry/asphyxia-cs2/issues/40#issuecomment-1956717482) to increase or decrease the pointer, the pointer 7 works and the CSkeletonInstance does not return null, but the CBoneData data is null

`	CSkeletonInstance* GetSkeletonInstance()
	{
		return MEM::CallVFunc<CSkeletonInstance*, 7U>(this);
	}
`

Well, these are my questions... thx!

**Comment by maecry** [comment]
if (GetBoneArray() && index < 0)

Yea i wonder why it always return nullptr

**Comment by SampleGH** [comment]
`	CSkeletonInstance* GetSkeletonInstance()
	{
		return MEM::CallVFunc<CSkeletonInstance*, 8U>(this);
	}`
	
`bool CGameSceneNode::GetBonePositionAndRotation(const std::int32_t bone_index,
Vector_t& bone_position,
Vector4D_t& bone_rotation)
{
	CSkeletonInstance* skeleton = GetSkeletonInstance();

	if (skeleton == nullptr)
		return false;

	const CModelState model_state = skeleton->m_modelState();

	const CBoneData* bone_array = model_state.bones;

	if (bone_array == nullptr)
		return false;

	const CBoneData& data = bone_array[bone_index];

	bone_position = data.position;
	bone_rotation = data.rotation;

	return true;
}`

This is how  i get my bone data

**Comment by XanaXCODE** [comment]
> if (GetBoneArray() && index < 0)
> 
> Yea i wonder why it always return nullptr
> 
> Edit: i mean u even try to return a vector_t pointer while its not even a ptr.... so many things wrong in ur code snippet

Sorry but i was not using GetBoneLocation, and I also didn't notice the error thx



> ```
> CSkeletonInstance* GetSkeletonInstance()
> {
> 	return MEM::CallVFunc<CSkeletonInstance*, 8U>(this);
> }
> ```
> 
> bool CGameSceneNode::GetBonePositionAndRotation(const std::int32_t bone_index, Vector_t& bone_position, Vector4D_t& bone_rotation) { CSkeletonInstance* skeleton = GetSkeletonInstance();
> 
> ```
> if (skeleton == nullptr)
> 	return false;
> 
> const CModelState model_state = skeleton->m_modelState();
> 
> const CBoneData* bone_array = model_state.bones;
> 
> if (bone_array == nullptr)
> 	return false;
> 
> const CBoneData& data = bone_array[bone_index];
> 
> bone_position = data.position;
> bone_rotation = data.rotation;
> 
> return true;
> ```
> 
> }
> 
> This is how i get my bone data
> 
> ![image](https://private-user-images.githubusercontent.com/163083553/312395975-1dc50da6-b564-4d11-9164-b3bde13f76e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgxNjUsIm5iZiI6MTcxMDMyNzg2NSwicGF0aCI6Ii8xNjMwODM1NTMvMzEyMzk1OTc1LTFkYzUwZGE2LWI1NjQtNGQxMS05MTY0LWIzYmRlMTNmNzZlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxMTA0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWM1YzMyNTliNjAwM2M3NmU4MDY2YjVjMTk3OTllNjdiN2NjYzI2ODVjNTk1NmExODhlY2I3OTlkMDZiMTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lXLawFm0jgDqRpAgDUzuq3h3GeX_qSv9i9b15oU49Y8)
> 
> edit: IDK why the code is not working with the code brackets here but just GetSkeletonInstance() function into CGameSceneNode inside of entity.h and then add this function to entity.cpp GetBonePositionAndRotation()

this continues to give me null, could I be calling it in a hook that doesn't support it?
`CSkeletonInstance* GetSkeletonInstance()
{
	return MEM::CallVFunc<CSkeletonInstance*, 8U>(this);
}`

**Comment by SampleGH** [comment]
> > if (GetBoneArray() && index < 0)
> > Yea i wonder why it always return nullptr
> > Edit: i mean u even try to return a vector_t pointer while its not even a ptr.... so many things wrong in ur code snippet
> 
> Sorry but i was not using GetBoneLocation, and I also didn't notice the error thx
> 
> > ```
> > CSkeletonInstance* GetSkeletonInstance()
> > {
> > 	return MEM::CallVFunc<CSkeletonInstance*, 8U>(this);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > bool CGameSceneNode::GetBonePositionAndRotation(const std::int32_t bone_index, Vector_t& bone_position, Vector4D_t& bone_rotation) { CSkeletonInstance* skeleton = GetSkeletonInstance();
> > ```
> > if (skeleton == nullptr)
> > 	return false;
> > 
> > const CModelState model_state = skeleton->m_modelState();
> > 
> > const CBoneData* bone_array = model_state.bones;
> > 
> > if (bone_array == nullptr)
> > 	return false;
> > 
> > const CBoneData& data = bone_array[bone_index];
> > 
> > bone_position = data.position;
> > bone_rotation = data.rotation;
> > 
> > return true;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > This is how i get my bone data
> > ![image](https://private-user-images.githubusercontent.com/163083553/312395975-1dc50da6-b564-4d11-9164-b3bde13f76e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjgxNjUsIm5iZiI6MTcxMDMyNzg2NSwicGF0aCI6Ii8xNjMwODM1NTMvMzEyMzk1OTc1LTFkYzUwZGE2LWI1NjQtNGQxMS05MTY0LWIzYmRlMTNmNzZlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxMTA0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWM1YzMyNTliNjAwM2M3NmU4MDY2YjVjMTk3OTllNjdiN2NjYzI2ODVjNTk1NmExODhlY2I3OTlkMDZiMTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lXLawFm0jgDqRpAgDUzuq3h3GeX_qSv9i9b15oU49Y8)
> > edit: IDK why the code is not working with the code brackets here but just GetSkeletonInstance() function into CGameSceneNode inside of entity.h and then add this function to entity.cpp GetBonePositionAndRotation()
> 
> this continues to give me null, could I be calling it in a hook that doesn't support it? edit: OnCreateMove `CSkeletonInstance* GetSkeletonInstance() { return MEM::CallVFunc<CSkeletonInstance*, 8U>(this); }`

This all works fine for me from CreateMove, how are u calling it??

this is how im doing skeleton ESP using it.

`
enum BONEINDEX : DWORD
{
	head = 6,
	neck_0 = 5,
	spine_1 = 4,
	spine_2 = 2,
	pelvis = 0,
	arm_upper_L = 8,
	arm_lower_L = 9,
	hand_L = 10,
	arm_upper_R = 13,
	arm_lower_R = 14,
	hand_R = 15,
	leg_upper_L = 22,
	leg_lower_L = 23,
	ankle_L = 24,
	leg_upper_R = 25,
	leg_lower_R = 26,
	ankle_R = 27,
};
`


`

	std::vector<std::pair<int, int>> boneConnections = {
		{ 0, 1 }, { 1, 2 }, { 2, 3 }, { 3, 4 }, // Spine and lower body
		{ spine_1, neck_0 }, // Upper Spine to Neck
		{ neck_0, head }, // Neck to Head
		{ spine_1, arm_upper_L }, // Upper Spine to Left Upper Arm
		{ arm_upper_L, arm_lower_L }, // Left Upper Arm to Left Lower Arm
		{ arm_lower_L, hand_L }, // Left Lower Arm to Left Hand
		{ spine_1, arm_upper_R }, // Upper Spine to Right Upper Arm
		{ arm_upper_R, arm_lower_R }, // Right Upper Arm to Right Lower Arm
		{ arm_lower_R, hand_R }, // Right Lower Arm to Right Hand
		{ spine_2, pelvis }, // Lower Spine to Pelvis
		{ pelvis, leg_upper_L }, // Pelvis to Left Upper Leg
		{ leg_upper_L, leg_lower_L }, // Left Upper Leg to Left Lower Leg
		{ leg_lower_L, ankle_L }, // Left Lower Leg to Left Ankle
		{ pelvis, leg_upper_R }, // Pelvis to Right Upper Leg
		{ leg_upper_R, leg_lower_R }, // Right Upper Leg to Right Lower Leg
		{ leg_lower_R, ankle_R } // Right Lower Leg to Right Ankle
	};

for (const auto& bonePair : boneConnections)
{
	int startBone = bonePair.first;
	int endBone = bonePair.second;

	Vector_t start, end;
	Vector4D_t boneRotation;

	if (pPawn->GetGameSceneNode()->GetBonePositionAndRotation(startBone, start, boneRotation) &&
	pPawn->GetGameSceneNode()->GetBonePositionAndRotation(endBone, end, boneRotation))
	{
		ImVec2 boneScreenPosition, boneScreenParentPosition;

		if (D::WorldToScreen(start, &boneScreenPosition) && D::WorldToScreen(end, &boneScreenParentPosition))
		{
			if (pPawn->can_see_player_position(pPawnLocal, pPawn, start) || (pPawn->can_see_player_position(pPawnLocal, pPawn, end)))
			{
				pDrawList->AddLine(
				ImVec2(boneScreenPosition.x, boneScreenPosition.y),
				ImVec2(boneScreenParentPosition.x, boneScreenParentPosition.y),
				colorVisible);
			}
			else
			{
				pDrawList->AddLine(
				ImVec2(boneScreenPosition.x, boneScreenPosition.y),
				ImVec2(boneScreenParentPosition.x, boneScreenParentPosition.y),
				colorInvisible);
			}
		}
	}
}
`

**Comment by ActuallyHex** [comment]
Just going to put this out there on how I got my bone data. Probably not the most ideal way to do it but it works well.

```
// inside your player loop
CSkeletonInstance* skeletoninstance = pPlayerPawn->GetGameSceneNode()->GetSkeletonInstance();

if (!skeletoninstance)
    return;

auto boneData = skeletoninstance->GetBoneData();

if (!boneData)
    return;

// head position would be
Vector_t head = boneData[6].pos; //  bone nums 0 - 30 if I remember correctly.
```

```
// CBoneData struct
struct CBoneData
{
	Vector_t pos;
	char pad[0x14];
};

// CSkeletonInstance Class
class CSkeletonInstance : public CGameSceneNode
{
public:
	SCHEMA_ADD_FIELD(CModelState, m_modelState, "CSkeletonInstance->m_modelState");
	SCHEMA_ADD_FIELD(int, m_nHitboxSet, "CSkeletonInstance->m_nHitboxSet");

	CBoneData* GetBoneData()
	{
		return *(CBoneData**)((DWORD64)this + 0x1E0);
	}
};
```
Skeleton ESP:
![image](https://github.com/maecry/asphyxia-cs2/assets/85820320/27d77377-d321-487f-a568-49351d5b9917)
