### ISSUE TITLE
broken chams

### ISSUE THREAD

**Issue by ghost** [maecry/asphyxia-cs2#53]
Chams don't work properly, invisible chams don't work at all

**Comment by Exlodium** [comment]
`
	// @note: SetCreateDataByMaterial failed on release build idk why
#ifdef _DEBUG
	I::MaterialSystem2->SetCreateDataByMaterial(pData, &pMatPrototype);
	pData->SetShaderType(szShaderType);

	pData->SetMaterialFunction(CS_XOR("F_DISABLE_Z_BUFFERING"), bDisableZBuffering ? 1 : 0);
	pData->SetMaterialFunction(CS_XOR("F_BLEND_MODE"), bBlendMode ? 1 : 0);
	pData->SetMaterialFunction(CS_XOR("F_TRANSLUCENT"), bTranslucent ? 1 : 0);

	CMaterial2** pMaterial;
	I::MaterialSystem2->CreateMaterial(&pMaterial, szName, pData);
	I::MemAlloc->Free(pData);
	return *pMaterial;
#endif
`
Note the comment above, the code snippet is from here
https://github.com/maecry/asphyxia-cs2/blob/2231fd62c27d71089ab7974a29b61b50044dad63/cstrike/features/visuals/chams.cpp#L186-L199

**Comment by maecry** [comment]
Seem like he deleted his acc
