### ISSUE TITLE
Adding a variable makes 146 errors in Dbghelp.h

### ISSUE THREAD

**Issue by BurAndBYsAlt** [maecry/asphyxia-cs2#54]
After adding a variable using `C_ADD_VARIABLE` on build the code starts returning 146 errors from windbg.h in the windows 10 sdk.

**To Reproduce**
* Add a boolean variable with any name using `C_ADD_VARIABLE` in variables.h 
* Use `C_GET` in an if statement
* Build code

**Expected behavior**
Not getting errors

**Additional context**
VS2022, c++20

**Comment by maecry** [comment]
u prob included the variables.h wrong

**Comment by BurAndBYsAlt** [comment]
> u prob included the variables.h wrong

I just used the default misc.cpp file and added an if statement there

**Comment by BurAndBYsAlt** [comment]
[Dbghelp is being called in the `config.h` file](1https://github.com/maecry/asphyxia-cs2/blob/master/cstrike/core/config.h#L7), which is the one I'm getting errors with.

**Comment by maecry** [comment]
> > u prob included the variables.h wrong
> 
> I just used the default misc.cpp file and added an if statement there

What exactly did u add since that only happened if u include the variables file in front of something

**Comment by BurAndBYsAlt** [comment]
Solution: Add above of dbghelp
```cpp
#include <Windows.h>
```

**Comment by BurAndBYsAlt** [comment]
P.S.: Not sure how it worked before but it probably needs an edit

**Comment by maecry** [comment]
> Solution: Add above of dbghelp
> 
> ```c++
> #include <Windows.h>
> #include <dbghelp.h>
> ```
> 
> Source: [StackOverflow](https://stackoverflow.com/a/43283926)

Really doesnt need as its included in config.cpp, looks at other files and see how i including file in order
