### ISSUE TITLE
Im not able to join matches?

### ISSUE THREAD

**Issue by lola123iuj** [maecry/asphyxia-cs2#55]
Im not able to join matches with the cheat injected? I know that its bannable i don't care about that. What can i change for the build to able to be used in cs2? and my launch options is empty.

![image](https://github.com/maecry/asphyxia-cs2/assets/163188256/64ba06c1-404d-4e7d-a869-dbf83b35e9be)

**Comment by maecry** [comment]
because loadlib call and the game detected non-authorized dll, u have to find a way to bypass this, ex manual map(read premake5.lua)
