### ISSUE TITLE
Access user's steam

### ISSUE THREAD

**Issue by Agzy-R** [maecry/asphyxia-cs2#56]
Just wanted to ask a question. How can I access the client's steam/steamid? I saw this feature in [https://github.com/bruhmoment21/cs2-sdk](url) but unfortunately the base was broken and I cannot use it anymore.

**Comment by maecry** [comment]
https://partner.steamgames.com/doc/sdk
Should be same w csgo

**Comment by Agzy-R** [comment]
Thanks, also another question. How can i access the localplayer FOV using camera services?

**Comment by maecry** [comment]
Look at entity.h
