### ISSUE TITLE
set offset values

### ISSUE THREAD

**Issue by Agzy-R** [maecry/asphyxia-cs2#57]
I am trying to add a feature such as "No Flash" and I need to change a offset value called "m_flFlashBangTime" but I don't know how to do that I'd appreciate it if someone gave me a snippet of a code to help.

**Comment by maecry** [comment]
https://github.com/maecry/asphyxia-cs2/blob/2231fd62c27d71089ab7974a29b61b50044dad63/cstrike/core/schema.h#L10
https://github.com/maecry/asphyxia-cs2/blob/2231fd62c27d71089ab7974a29b61b50044dad63/cstrike/core/schema.h#L16
```
float& a = pLocal->GetFlashBangTime();
a=0;

// or
pLocal->GetFlashBangTime() = 0;
```

**Comment by Agzy-R** [comment]
Sorry I'm being a little dumb but here is what I tried.

`class C_CSWORLD
{
public:
	SCHEMA_ADD_FIELD(bool, GetC4Activated, "C_PlantedC4->m_bC4Activated");
	SCHEMA_ADD_OFFSET(float, GetFlashBangTime, 0x17371A8 + 0x14B8);
};
`

> Here are the offsets: dwLocalPlayerPawn = 0x17371A8 | m_flFlashBangTime = 0x14B8;

`
float& flashTime = world.GetFlashBangTime();
flashTime = 0;
`

I tried this but game crashes
