### ISSUE TITLE
nButtons &= ~IN_ATTACK stuck

### ISSUE THREAD

**Issue by Tusso4** [maecry/asphyxia-cs2#58]
Hi, im trying to fix my aimbot cause pistols shots only 1 shoot.

When i do nButtons |= IN_ATTACK it shoot but i cant unset in_attack cause if i did it my game not shoot.
And if i dont clear in_attack, it shoot and still holding...

In unknowncheats told me "change CMD to 0x54" but i dont understand at all.... anyone can help me to fix it and fix in base too?

Thanks!

**Comment by maecry** [comment]
I don't think this is a base's problem
