### ISSUE TITLE
** Outdated patterns **

### ISSUE THREAD

**Issue by Agzy-R** [maecry/asphyxia-cs2#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Agzy-R** [comment]
48 89 5C 24 00 48 89 6C 24 00 56 57 41 56 48 81 EC 00 00 00 00 48 8D 0D

**Comment by maecry** [comment]
fixed in latest commit maybe. dk if there is still something left
