### ISSUE TITLE
doesnt work :(

### ISSUE THREAD

**Issue by podushka123** [maecry/asphyxia-cs2#63]
After the last update, when I inject the cheat in default mode nothing happens (I tried to open the menu on insert), in debug mode it crashes and the console is empty.
please help

**Comment by maecry** [comment]
![image](https://github.com/maecry/asphyxia-cs2/assets/52035116/b0fddef8-1817-4ed6-8d47-dfa2ec3b3b36)
worked fine on latest commit, pull it lol
