### ISSUE TITLE
Crash On inject

### ISSUE THREAD

**Issue by Elomental** [maecry/asphyxia-cs2#68]
I pasted the new update but it still crashes. I even downloaded from github itself and tried to inject but it crashes in lobby without giving any errors

**Comment by maecry** [comment]
#67 no debug attached and log show

**Comment by Elomental** [comment]
How am i supposed to show you logs when nothing gets outputted and there is no errors. I literally download the project from github and tried to inject and it crashed.

**Comment by maecry** [comment]
> How am i supposed to show you logs when nothing gets outputted and there is no errors. I literally download the project from github and tried to inject and it crashed.

attach the debugger? show the callstack and stuffs, I literally said so in #67

**Comment by maecry** [comment]
learn how to use the debugger https://www.youtube.com/watch?v=__3wlUxMXlA
