### ISSUE TITLE
"Crash" of cheat

### ISSUE THREAD

**Issue by milsnel** [maecry/asphyxia-cs2#69]
Since the last update, you have changed the logic of operation CORE::GetWorkingPath, and 
GetModuleFileNameW always returns false, after that the hack is closed, to fix it is enough to go back to the previous version and everything works as before again. 
OS: Windows 11 23H2 (22631.3447)

**Comment by maecry** [comment]
Doesn't happened to me so its a your pc issue

**Comment by maecry** [comment]
But yea ill change that too mem::getbassemdlfilename

**Comment by maecry** [comment]
should be fixed ur issue now as I stopped  using the winapi for getworkingpath 2590403370a0212b5ebbceb6892959774d876259
