### ISSUE TITLE
Pattern Error

### ISSUE THREAD

**Issue by Source1pt** [maecry/asphyxia-cs2#70]
[memory.cpp:220] [error] export not found: UnDecorateSymbolName
[memory.cpp:220] [error] export not found: SDL_SetRelativeMouseMode
[memory.cpp:220] [error] export not found: SDL_SetWindowGrab
[memory.cpp:220] [error] export not found: SDL_WarpMouseInWindow
[memory.cpp:220] [error] export not found: ?LoadKV3@@YA_NPEAVKeyValues3@@PEAVCUtlString@@PEBDAEBUKV3ID_t@@2@Z
[memory.cpp:356] [error] pattern not found: "48 89 5C 24 00 48 89 6C 24 00 56 57 41 56 48 81 EC 00 00 00 00 48 8B 05"

**Comment by maecry** [comment]
![image](https://github.com/maecry/asphyxia-cs2/assets/52035116/2da40743-2298-488f-b06c-507af7355784)
doesn't happened on my end

**Comment by maecry** [comment]
and #67 as you doesn't even provide call stack etc

**Comment by Source1pt** [comment]
what injector do you use?

**Comment by maecry** [comment]
any loadlibrary injector
