### ISSUE TITLE
question: Where is cs2 schema field

### ISSUE THREAD

**Issue by Source1pt** [maecry/asphyxia-cs2#72]
Since the 2 last updates, I think you removed the schema dump. Now there is only offsets. Does asphyxia still dump the cs2 schema? if no than is there a place to get it?

**Comment by maecry** [comment]
https://github.com/maecry/asphyxia-cs2/blob/9ea1a5f890ad26ca749a7bd74474120f1aedb36f/cstrike/core.cpp#L135

Still dumping

And
https://github.com/maecry/asphyxia-cs2/blob/9ea1a5f890ad26ca749a7bd74474120f1aedb36f/cstrike/core.cpp#L39
Dump folder is now where you placed the dll
