### ISSUE TITLE
cheat not working because of cs2 update

### ISSUE THREAD

**Issue by bebrikpopka** [maecry/asphyxia-cs2#79]
cheat not working because of cs2 update, injector log - returned NULL

**Comment by execnone** [comment]
crash at SCHEMA::Setup()

// allocate memory for elements
UtlTSHashHandle_t* pElements = new UtlTSHashHandle_t[nTableSize + 1U];
const auto nElements = pTypeScope->hashClasses.GetElements(0, nTableSize, pElements); <- crash

**Comment by pogrammerX** [comment]
yup same here, i think that the ``FindTypeScopeForModule`` vtable index changed

**Comment by Exlodium** [comment]
Issue resolved with latest commit
[https://github.com/maecry/asphyxia-cs2/commit/21694a7579ca60d9cb8597c397666f0b637834b5](url)
