### ISSUE TITLE
Injecting not working when adding /Zc:threadSafeInit- 

### ISSUE THREAD

**Issue by xdCraze** [maecry/asphyxia-cs2#84]
So I'm trying to inject this .dll without -insecure enabled, and I read to add /Zc:threadSafeInit- to additional options when building. But, that didn't change anything. It still crashes on injection. So I'm kinda out of luck. I'm too lazy to make my own injector, and I've tried a ton of other injectors and none of them work.
![Screenshot 2024-06-06 115657](https://github.com/maecry/asphyxia-cs2/assets/167240403/9d6c4e8e-dd84-4ab5-929e-d0cf162de75e)

**Comment by maecry** [comment]
Injector issue and plenty things could happen, just use loadlib and bypass stuffs there better than fixing dependencies
