### ISSUE TITLE
Get_RelativeMouseMode issue

### ISSUE THREAD

**Issue by iMoszczak** [maecry/asphyxia-cs2#89]
**Describe the bug**
Mouse stays visible after closing menu in game.

**To Reproduce**
Open menu, close menu.

**Expected behavior**
Mouse is no longer visible after closing menu in game.

**Screenshots**
(https://github.com/maecry/asphyxia-cs2/assets/49692924/9b5a52e5-8153-46e4-a25e-650298e2a2ab)

**Comment by Exlodium** [comment]
I'll check it out. Just quickly tested the implementation before pushing. 

Sorry about the inconvenience

**Comment by lagcompensation** [comment]
btw i think its easy to fix
u need to hook IsRelativeMouseMode and call original in wndproc 
like it
`hooks::o_is_relative_mouse_mode(  valve::g_input_system, g_menu->opened( ) ? false : g_menu->last_active( ) )`

**Comment by iMoszczak** [comment]
> btw i think its easy to fix u need to hook IsRelativeMouseMode and call original in wndproc like it `hooks::o_is_relative_mouse_mode( valve::g_input_system, g_menu->opened( ) ? false : g_menu->last_active( ) )`

could you make a pull request?

**Comment by lagcompensation** [comment]
> > btw i think its easy to fix u need to hook IsRelativeMouseMode and call original in wndproc like it `hooks::o_is_relative_mouse_mode( valve::g_input_system, g_menu->opened( ) ? false : g_menu->last_active( ) )`
> 
> could you make a pull request?

done

**Comment by iMoszczak** [comment]
> > > btw i think its easy to fix u need to hook IsRelativeMouseMode and call original in wndproc like it `hooks::o_is_relative_mouse_mode( valve::g_input_system, g_menu->opened( ) ? false : g_menu->last_active( ) )`
> > 
> > 
> > could you make a pull request?
> 
> done

thanks
