### ISSUE TITLE
Manual Map Crash Injection

### ISSUE THREAD

**Issue by gi-glitch** [maecry/asphyxia-cs2#90]
It is assumed that enabling "/Zc:threadSafeInit-" would not have any problem with injecting manual map, the issue is that it crashes instantly, I tried it from premake5, manually in visual studio, but the parameter /Zc:threadSafeInit- does not work, is there something else that could be generating the crash? The only thing I have seen from the other posts about this is "use loadlibrary or enable /Zc:threadSafeInit-", I really like your source is a very well done work, but I do not want to use loadlibrary and host the DLL on my PC, I find it much more comfortable to inject the byte array of the dll, hopefully you have idea of an alternative to this :), thank you

**Comment by gi-glitch** [comment]
(I'm not a troll, I don't use github, that's why the account just created)

**Comment by maecry** [comment]
'more comfortable to inject the byte array of the dll'

lol you know loadlibrary can also do this, and not only threadsafeinit needed to be enable for manualmapping to work, it's also part of injector's problem and how can I know ur injector lol, it's your issue and this base will never support manual map injector(for now)

**Comment by gi-glitch** [comment]
So why do you say it's a problem of my injector when you tell me at the end "it doesn't support manual map"? 💀

**Comment by maecry** [comment]
support here as mean in supporting issue like this
