### ISSUE TITLE
Bug with config systemg

### ISSUE THREAD

**Issue by Lok3rn3t** [maecry/asphyxia-cs2#96]
**Describe the bug**
The error is that each of the following configs has missing characters in its name

**To Reproduce**
Сreating a large number of configurations

**Expected behavior**
Loss of characters

**Additional context**
Specifically these lines of code are causing the problem, or rather the converter is causing the problem
```cpp
CRT::String_t<MAX_PATH> szFileName(C::vecFileNames[i]);
if (ImGui::Selectable(szFileName.Data(), (nSelectedConfig == i)))
	nSelectedConfig = i;
```
I use a similar method to solve the problem, although it is not the best one
```cpp
std::string wchar_to_string(const wchar_t* wchar_str)
{
	std::wstring ws(wchar_str);
	std::string str(ws.begin(), ws.end());
	return str;
}
if (ImGui::Selectable(wchar_to_string(C::vecFileNames[i]).c_str(), (nSelectedConfig == i))) {}

**Comment by maecry** [comment]
looks like you don't know what u're doing... and large charater will be replace with "..." iirc

**Comment by Lok3rn3t** [comment]
You don't have the conversions done correctly, which is causing some horrible stuff to happen in the buffer

**Comment by maecry** [comment]
it done correctly on my machine so idk what u talking about

**Comment by Lok3rn3t** [comment]
Do you create a lot of configs and you don't have any problems at all?

**Comment by maecry** [comment]
i don't see the reason of making like 300 config files so no it's not an issue

**Comment by Lok3rn3t** [comment]
that's how I get jokes from 3-4 configurations onwards, I don't know if it's my operating system language.

**Comment by maecry** [comment]
could be as the menu's font doesnt support unicode(Verdana moment) and the things i put there are really stupid way to handle different dpi scalling(just need 1 font with biggest size and imgui will handle the resize stuffs but yea idc atm)

**Comment by Lok3rn3t** [comment]
![изображение](https://github.com/maecry/asphyxia-cs2/assets/71749209/ea6ad5c7-0d64-4a9f-8f78-6177b50adf99)
![изображение](https://github.com/maecry/asphyxia-cs2/assets/71749209/48de2206-005c-4213-91b1-e83dcc1fe725)
Maybe this will help you

**Comment by maecry** [comment]
yea idk fixed now
